// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MintPlayerCrawler.Data;

namespace MintPlayerCrawler.Data.Migrations
{
    [DbContext(typeof(MintPlayerCrawlerContext))]
    [Migration("20190923160609_AddLinks")]
    partial class AddLinks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MintPlayerCrawler.Data.Entities.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url");

                    b.Property<int?>("ViaId");

                    b.HasKey("Id");

                    b.HasIndex("ViaId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("MintPlayerCrawler.Data.Entities.Link", b =>
                {
                    b.HasOne("MintPlayerCrawler.Data.Entities.Link", "Via")
                        .WithMany()
                        .HasForeignKey("ViaId");
                });
#pragma warning restore 612, 618
        }
    }
}
