// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MintPlayerCrawler.Data;

namespace MintPlayerCrawler.Data.Migrations
{
    [DbContext(typeof(MintPlayerCrawlerContext))]
    [Migration("20190923160643_AddJobs")]
    partial class AddJobs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MintPlayerCrawler.Data.Entities.Jobs.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JobType")
                        .IsRequired();

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasDiscriminator<string>("JobType").HasValue("Job");
                });

            modelBuilder.Entity("MintPlayerCrawler.Data.Entities.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url");

                    b.Property<int?>("ViaId");

                    b.HasKey("Id");

                    b.HasIndex("ViaId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("MintPlayerCrawler.Data.Entities.Jobs.FetchUrlsJob", b =>
                {
                    b.HasBaseType("MintPlayerCrawler.Data.Entities.Jobs.Job");

                    b.Property<string>("Html");

                    b.Property<string>("Url");

                    b.HasDiscriminator().HasValue("fetch_urls");
                });

            modelBuilder.Entity("MintPlayerCrawler.Data.Entities.Jobs.IndexJob", b =>
                {
                    b.HasBaseType("MintPlayerCrawler.Data.Entities.Jobs.Job");

                    b.Property<string>("Html")
                        .HasColumnName("IndexJob_Html");

                    b.Property<string>("Url")
                        .HasColumnName("IndexJob_Url");

                    b.HasDiscriminator().HasValue("index");
                });

            modelBuilder.Entity("MintPlayerCrawler.Data.Entities.Jobs.RequestJob", b =>
                {
                    b.HasBaseType("MintPlayerCrawler.Data.Entities.Jobs.Job");

                    b.Property<string>("Url")
                        .HasColumnName("RequestJob_Url");

                    b.HasDiscriminator().HasValue("request");
                });

            modelBuilder.Entity("MintPlayerCrawler.Data.Entities.Link", b =>
                {
                    b.HasOne("MintPlayerCrawler.Data.Entities.Link", "Via")
                        .WithMany()
                        .HasForeignKey("ViaId");
                });
#pragma warning restore 612, 618
        }
    }
}
