using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.DependencyInjection;
using MintPlayer.Spark.Authorization.Identity;
using Spike.Migration.Totp;

namespace Spike.Migration;

/// <summary>
/// 2FA (TOTP) continuity — existing authenticator enrollments keep working after migration without
/// re-enrollment. The ETL copies the Base32 authenticator secret from AspNetUserTokens
/// (LoginProvider='[AspNetUserStore]', Name='AuthenticatorKey') into <see cref="SparkUser.AuthenticatorKey"/>.
/// A code generated by an INDEPENDENT RFC-6238 implementation (<see cref="Authenticator"/>, standing
/// in for the user's phone app) is validated through Identity's real AuthenticatorTokenProvider.
/// </summary>
public class TwoFactorContinuityTests : AuthSpikeBase
{
    // Base32 of the ASCII secret "12345678901234567890" (RFC 6238 reference key).
    private const string AuthenticatorKey = "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ";

    [Fact]
    public async Task Migrated_authenticator_key_validates_a_live_TOTP_code()
    {
        var sp = BuildIdentityServices();
        using var scope = sp.CreateScope();
        var userManager = scope.ServiceProvider.GetRequiredService<UserManager<SparkUser>>();

        // --- ETL: user migrated with TwoFactor enabled and the secret copied verbatim ---
        var migrated = new SparkUser
        {
            UserName = "carol",
            NormalizedUserName = "CAROL",
            Email = "carol@example.com",
            NormalizedEmail = "CAROL@EXAMPLE.COM",
            TwoFactorEnabled = true,
            AuthenticatorKey = AuthenticatorKey,
        };

        string id;
        using (var store = new UserStore<SparkUser>(Store))
        {
            (await store.CreateAsync(migrated, CancellationToken.None)).Succeeded.Should().BeTrue();
            id = migrated.Id!;
        }

        var user = await userManager.FindByIdAsync(id);
        user.Should().NotBeNull();
        user!.AuthenticatorKey.Should().Be(AuthenticatorKey, "the secret is copied verbatim");
        user.TwoFactorEnabled.Should().BeTrue();

        // --- The user's existing authenticator app generates the current code ---
        var code = Authenticator.GenerateCode(AuthenticatorKey);

        // --- Spark/Identity validates it against the migrated key ---
        var valid = await userManager.VerifyTwoFactorTokenAsync(
            user, TokenOptions.DefaultAuthenticatorProvider, code);
        valid.Should().BeTrue("a code from the enrolled app must still verify after migration");

        var wrong = await userManager.VerifyTwoFactorTokenAsync(
            user, TokenOptions.DefaultAuthenticatorProvider, "000000");
        wrong.Should().BeFalse();
    }
}
